---
# * User 'admin' should exist with sudo privileges.
# * Copy control machine public key to host.
#
# NB: If you want to change the list of domains registered with master
# certificate after the original deployment:
# 1. Use the manual renewal command:
#
# certbot --apache certonly --cert-name jenkins.artex.ai-em.net \
#   [-d domain1] [-d domain2] [-d domain3] etc
#
# 2. Add the new domains to 'build/host_vars/build'
#
# 3. Then re-deploy the ansible playbook:
# (ansible-playbook ../boot.yml -e "use_no_certs=false")
#
# 4. Then run the crontab renewal command. (Inspect with crontab -l).
# See https://certbot.eff.org/docs/using.html?highlight=domain#changing-a-certificate-s-domains.
#
# To run create manually for first time:
#
# certbot --apache certonly --expand --noninteractive --agree-tos --email mike@ai-em.net [-d domain1 ] etc

- hosts: control
  vars:
    env: "{{ (my_env is not defined or my_env is none) | ternary('build', my_env) }}"
  tasks:
  - name: set correct user
    set_fact:
      ansible_user: "admin"
    when: env == "build"
  - name: output admin user
    debug:
      var: ansible_user
  - name: output env
    debug:
      var: env
  - name: read encrypted values
    include_vars:
      file: "{{ playbook_dir }}/encrypted"
      name: vault_vals
  - name: install passlib
    pip:
      virtualenv: "{{ playbook_dir }}/python"
      name:
        - passlib
  - name: create htpasswd file for femarkup
    htpasswd:
      path: "{{ playbook_dir }}/build/docker/jenkinspw"
      name: "{{ basic_user }}"
      password: "{{ basic_password }}"
      mode: 0640
  - name: create git folder
    file:
      path: "{{ playbook_dir }}/files/git"
      state: directory

- hosts: build
  vars:
    env: "{{ (my_env is not defined or my_env is none) | ternary('build', my_env) }}"
    ansible_python_interpreter: /usr/bin/python
  roles:
    - { role: geerlingguy.docker, when: env == "build" }
  tasks:
    - name: set correct user
      set_fact:
        ansible_user: "admin"
      when: env == "build"
    - name: install packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - certbot
          - snapd
          - apache2
          - virtualenv
          - libxml-twig-perl
          - rsync
      when: env == "build"
    - name: remove pre-existing virtualenv
      file:
        state: absent
        path: /opt/python
    - name: create virtualenv
      command:
        cmd: virtualenv /opt/python -p python2.7
        creates: "/opt/python"
    - name: install snap core
      snap:
        name:
          - core
    - name: install snap certbot
      snap:
        name: certbot
        classic: yes
    - name: rename old
      command: mv /usr/bin/certbot /usr/bin/certbot.old
    - name: "Create link"
      file:
        path=/usr/bin/certbot
        src=/snap/bin/certbot
        state=link

- hosts: build
  vars:
    env: "{{ (my_env is not defined or my_env is none) | ternary('build', my_env) }}"
  tasks:
    - name: install python docker
      pip:
        virtualenv: /opt/python
        name:
          - docker-compose
      when: env == "build"

- hosts: build
  vars:
    certbot_dir: /snap/bin
    certbot_script: "{{ certbot_dir }}/certbot"
    certbot_install_from_source: false
    certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
    certbot_auto_renew_minute: "20"
    certbot_auto_renew_hour: "5"
    certbot_auto_renew_options: "--apache --quiet --no-self-upgrade --pre-hook='/home/{{ ansible_user }}/certbot-hooks.sh pre' --post-hook='/home/{{ ansible_user }}/certbot-hooks.sh post' --deploy-hook='/home/{{ ansible_user }}/certbot-hooks.sh deploy'"
    certbot_create_command: "{{ certbot_script }} --apache certonly --expand --noninteractive --agree-tos --email {{ cert_item.email | default(certbot_admin_email) }} -d {{ cert_item.domains | join(',') }}"
    certbot_certs:
      - email: mike@ai-em.net
        domains: "{{ domains }}"
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_admin_email: mike@ai-em.net
    certbot_create_standalone_stop_services: []
    no_certs: "{{ (use_no_certs == 'true') | ternary(true, false) }}"
    env: "{{ (my_env is not defined or my_env is none) | ternary('build', my_env) }}"
  gather_facts: yes
  roles:
  - { role: geerlingguy.certbot, when: no_certs == false }
  tasks:
  - name: set correct user
    set_fact:
      ansible_user: "admin"
    when: env == "build"
  - name: read encrypted values
    include_vars:
      file: "{{ playbook_dir }}/encrypted"
      name: vault_vals
  - fail:
      msg: "AWS secret access key is required"
    when: aws_secret_access_key == ""
  - fail:
      msg: "AWS access key id is required"
    when: aws_access_key_id == ""
  - name: adding vagrant to group docker
    user:
      name: "{{ ansible_user }}"
      groups: docker
      append: yes
  - name: create jenkins mount dir
    file:
      path: "/home/{{ ansible_user }}/jenkins"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: create bbgateway mount dir
    file:
      path: "/home/{{ ansible_user }}/bbgateway"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: rsync gateway files
    synchronize:
      src: "{{ playbook_dir }}/misc/bitbucket-rog/"
      dest: "/home/{{ ansible_user }}/bbgateway"
      rsync_opts:
        - "--exclude=node_modules"
  - name: create nginx-proxy certs mount dir
    file:
      path: "/home/{{ ansible_user }}/nginx-certs"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    when: no_certs == false
  - name: create nginx-proxy vhost.d dir
    file:
      path: "/home/{{ ansible_user }}/vhost.d"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: copy hooks script
    template:
      src: "{{ playbook_dir }}/build/certbot-hooks.j2"
      dest: "/home/{{ ansible_user }}/certbot-hooks.sh"
      mode: 0500
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    when: no_certs == false
  - name: copy cert file
    with_items: "{{ domains }}"
    copy:
      src: "/etc/letsencrypt/live/{{ domains[0] }}/privkey.pem"
      dest: "/home/{{ ansible_user }}/nginx-certs/{{ item }}.key"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      remote_src: true
      mode: 0500
    when: no_certs == false
  - name: copy cert file
    with_items: "{{ domains }}"
    copy:
      src: "/etc/letsencrypt/live/{{ domains[0] }}/chain.pem"
      dest: "/home/{{ ansible_user }}/nginx-certs/{{ item }}.csr"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      remote_src: true
      mode: 0500
    when: no_certs == false
  - name: copy cert file
    with_items: "{{ domains }}"
    copy:
      src: "/etc/letsencrypt/live/{{ domains[0] }}/fullchain.pem"
      dest: "/home/{{ ansible_user }}/nginx-certs/{{ item }}.crt"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      remote_src: true
      mode: 0500
    when: no_certs == false
  - name: generate dhparam
    with_items: "{{ domains }}"
    openssl_dhparam:
      path: "/home/{{ ansible_user }}/nginx-certs/{{ item }}.dhparam.pem"
      size: 2048
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: 0500
    when: no_certs == false
  - name: create docker compose dir
    file:
      path: "/home/{{ ansible_user }}/docker"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: insert docker compose file
    template:
      src: "{{ playbook_dir }}/build/docker/docker-compose.j2"
      dest: "/home/{{ ansible_user }}/docker/docker-compose.yml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: copy pw file
    copy:
      src: "{{ playbook_dir }}/build/docker/jenkinspw"
      dest: "/home/{{ ansible_user }}/docker/"
      group: "{{ ansible_user }}"
      owner: "{{ ansible_user }}"
  - name: copy backup scripts
    copy:
      src: "{{ playbook_dir }}/build/backups"
      dest: "/home/{{ ansible_user }}"
      group: "{{ ansible_user }}"
      owner: "{{ ansible_user }}"
  - name: make backup script exectuable
    file: "dest=/home/{{ ansible_user }}/backups/bin/backups mode=a+x"
  - name: create nginx network
    docker_network:
      name: nginx-proxy
      state: present
  - name: log into docker registry
    docker_login:
      registry: https://registry.gitlab.com
      username: "{{ docker_registry_user }}"
      # gitlab personal access token (which can read registry) due to expire 01/12/2020!
      password: "{{ docker_registry_password }}"
      reauthorize: yes
      # make result of login available to 'vagrant' user
      config_path: "/home/{{ ansible_user }}/.docker/config.json"
    become_user: "{{ ansible_user }}"
  - name: Stop service httpd, if started
    ansible.builtin.service:
      name: apache2
      state: stopped
  - name: stop services
    become_user: "{{ ansible_user }}"
    docker_compose:
      project_src: "/home/{{ ansible_user }}/docker"
      build: no
      stopped: yes
  - name: run jenkins/proxy service
    become_user: "{{ ansible_user }}"
    docker_compose:
      project_src: "/home/{{ ansible_user }}/docker"
      state: present
    with_items:
    - "{{ aws_secret_access_key }}"
    - "{{ aws_access_key_id }}"
  - name: create aws config dir
    file:
      path: "/home/{{ ansible_user }}/jenkins/.aws"
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: insert aws credentials file
    template:
      src: "{{ playbook_dir }}/build/aws-credentials.j2"
      dest: "/home/{{ ansible_user }}/jenkins/.aws/credentials"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: create aws backup config dir
    file:
      path: /tmp/.aws
      state: directory
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  - name: insert aws credentials file (backup)
    template:
      src: "{{ playbook_dir }}/build/aws-credentials.j2"
      dest: /tmp/.aws/credentials
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
  # create symlink to enable build-dev builds to work correctly
  - name: create admin symlink
    file:
      src: /home/vagrant
      dest: /home/admin
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: link
    when: env == "build-dev"
...
