---
- hosts: node
  vars:
    devops_tools: "{{ (install_devops_tools is defined and install_devops_tools == 'true') | ternary(true, false) }}"
    env: "{{ (my_env is defined) | ternary(my_env, 'dev') }}"
    no_clone: "{{ (git_no_clone is defined and git_no_clone == 'true') | ternary(true, false) }}"
    rebuild: "{{ (docker_rebuild is defined and docker_rebuild == 'true') | ternary(true, false) }}"
    branch_type: ""
  gather_facts: yes
  tasks:
    - name: setup "dev" environment
      block:
        - name: read encrypted values
          include_vars:
            file: "{{ playbook_dir }}/encrypted"
            name: vault_vals
        - name: project(s) dir
          file:
            path: /home/vagrant/files
            state: directory
            owner: vagrant
            group: vagrant
        - name: Check micro1 repo has already been cloned
          stat:
            path: "/home/vagrant/files/project/.git"
          register: micro1_repo
        - name: Clone private repository
          git:
            repo: git@bitbucket.org:gigabyte-software/micro1.git
            version: master
            dest: /home/vagrant/files/project
            accept_hostkey: yes
            clone: yes
          become_user: vagrant
          when: not no_clone and not micro1_repo.stat.exists
        - name: Check fe repo has already been cloned
          stat:
            path: "/home/vagrant/files/fe/.git"
          register: fe_repo
        - name: Clone private fe repository
          git:
            repo: git@bitbucket.org:gigabyte-software/fe1.git
            version: master
            dest: /home/vagrant/files/fe
            accept_hostkey: yes
          become_user: vagrant
          when: not no_clone and not fe_repo.stat.exists
        - name: grab docker-compose template
          fetch:
            src: /home/vagrant/files/project/env/docker-compose.yml.j2
            dest: "{{ playbook_dir }}/tmp/docker-compose.yml.j2"
            flat: true
        # branch is irrelevant in "dev" environment
        - name: set branch id
          set_fact:
            branch_id: "0"
        - name: insert docker-compose file
          template:
            src: "{{ playbook_dir }}/tmp/docker-compose.yml.j2"
            dest: /home/vagrant/files/project/docker-compose.yml
        - name: grab dotenv "dist"
          fetch:
            src: /home/vagrant/files/project/env/dotenv.j2
            dest: "{{ playbook_dir }}/tmp/dotenv.j2"
            flat: true
        - name: insert dotenv file
          template:
            src: "{{ playbook_dir }}/tmp/dotenv.j2"
            dest: /home/vagrant/files/project/.env
        - name: create docker config dir
          file:
            path: /home/vagrant/.docker
            state: directory
            owner: vagrant
            group: vagrant
        - name: create docker config file
          file:
            path: /home/vagrant/.docker/config.json
            state: touch
            owner: vagrant
            group: vagrant
        - name: log into docker registry
          docker_login:
            registry: https://registry.gitlab.com
            username: "{{ docker_registry_user }}"
            # gitlab personal access token (which can read registry) due to expire 01/12/2020!
            password: "{{ docker_registry_password }}"
            reauthorize: yes
            # make result of login available to 'vagrant' user
            config_path: /home/vagrant/.docker/config.json
        - name: create mongodb data dir
          file:
            path: /home/vagrant/db
            state: directory
            owner: vagrant
            group: vagrant
        - name: run the service
          become_user: vagrant
          docker_compose:
            project_src: /home/vagrant/files/project
            build: "{{ rebuild }}"
            #        nocache: "{{ rebuild }}"
            pull: "{{ rebuild }}"
            state: present
        - name: get composer
          get_url:
            dest: /home/vagrant/files/project
            url: http://getcomposer.org/composer.phar
        - name: devdeps permissions
          file:
            path: /home/vagrant/files/project/env/devdeps.sh
            owner: vagrant
            group: vagrant
            mode: '0744'
        - name: install dev deps
          command: docker exec -it -u www-data app /bin/bash ./env/devdeps.sh
          args:
            chdir: /home/vagrant/files/project
          become_user: vagrant

        # there are potential issues caused when symfony attempts to clear it's cache
        # after composer install, caused by files found in the default cache location of "/tmp".
        # therefore remove the "devdeps" working directory
        # @TODO: consider using a different location for the "devdeps" dir
        - name: remove devdeps working dir
          command: docker exec -it app rm -rf /tmp/project
          args:
            chdir: /home/vagrant/files/project
          become_user: vagrant
        - name: build/test project
          command: docker exec -u www-data app ant
          args:
            chdir: /home/vagrant/files/project
          become_user: vagrant
      when: devops_tools == false

- hosts: control
  vars:
    devops_tools: "{{ (install_devops_tools is defined and install_devops_tools == 'true') | ternary(true, false) }}"
  gather_facts: yes
  tasks:
    - name: install devops tools
      block:
        - name: read encrypted values
          include_vars:
            file: "{{ playbook_dir }}/encrypted"
            name: vault_vals
        - name: install utilities
          apt:
            name:
              - unzip
              - jq
            state: present
        - name: download terraform
          get_url:
            url: https://releases.hashicorp.com/terraform/0.12.20/terraform_0.12.20_linux_amd64.zip
            dest: /root
          become: yes
        - name: unzip terraform
          unarchive:
            src: /root/terraform_0.12.20_linux_amd64.zip
            dest: /root
            remote_src: yes
          become: yes
        - name: install terraform
          command: mv /root/terraform /usr/local/bin/terraform
          become: yes
        - name: remove terraform download
          file:
            path: /root/terraform_0.12.20_linux_amd64.zip
            state: absent
          become: yes
        - name: download terragrunt
          get_url:
            url: https://github.com/gruntwork-io/terragrunt/releases/download/v0.21.11/terragrunt_linux_amd64
            dest: /root
          become: yes
        - name: install terragrunt
          command: mv /root/terragrunt_linux_amd64 /usr/local/bin/terragrunt
          become: yes
        - name: terragrunt permissions
          file:
            path: /usr/local/bin/terragrunt
            mode: '0755'
          become: yes
        - name: install aws cli
          pip:
            name:
              - awscli
          become: yes
      when: devops_tools == true
...

